services:
 mysql_db:
  image: mysql
  container_name: db_name
  environment:
   MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
  secrets:
   - db_root_password

 nginx_revers_proxy:
  image: nginx
  restart: always
  ports:
   - 8080:80
  container_name: proxy_name

secrets:
 db_root_password:
  file: ./db_root_password
